src/AppBundle/Entity/Book.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Book
 *
 * @ORM\Table(name="book")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\BookRepository")
 * @Vich\Uploadable
 */
class Book
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=1024)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="author", type="string")
     */
    private $author;


    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Category", inversedBy="books")
     */
    private $categories;


    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Reader", mappedBy="books")
     */
    private $readers;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="book_image", fileNameProperty="imageName")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $imageName;


    /**
     * @var \DateTime
     * @ORM\Column(type="date", nullable=true)
     */
    private $expected_return_date = null;

    /**
     * @var \DateTime
     * @ORM\Column(type="date", nullable=true)
     */
    private $fixed_return_date = null;


    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    private $status = true;
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile($image = null)
    {
        $this->imageFile = $image;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageName($imageName)
    {
        $this->imageName = $imageName;
    }

    public function getImageName()
    {
        return $this->imageName;
    }


    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->readers = new ArrayCollection();
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Book
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set author
     *
     * @param string $author
     *
     * @return Book
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }


    public function addCategory($category)
    {
        $this->categories->add($category);

        return $this;
    }


    public function getCategories()
    {
        return $this->categories;
    }


    public function addReader($reader)
    {
        $this->readers->add($reader);
        $reader->addBook($this);

        return $this;
    }

    public function getReaders()
    {
        return $this->readers;
    }

    /**
     * @param \DateTime $fixed_return_date
     * @return Book
     */
    public function setFixedReturnDate(\DateTime $fixed_return_date)
    {
        $this->fixed_return_date = $fixed_return_date;
        return $this;
    }

    /**
     * @return string
     */
    public function getFixedReturnDateString()
    {
        return date_format($this->fixed_return_date, 'Y-m-d');
    }

    /**
     * @param string $expected_return_date
     * @return Book
     */
    public function setExpectedReturnDate(string $expected_return_date)
    {
        $this->expected_return_date = date_create_from_format('Y-m-d', $expected_return_date);
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getExpectedReturnDateString()
    {
        return date_format($this->expected_return_date, 'Y-m-d');
    }

    /**
     * @param bool $status
     * @return Book
     */
    public function setStatus(bool $status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return bool
     */
    public function isStock()
    {
        return $this->status;
    }
}

src/AppBundle/Controller/MainController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Reader;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class MainController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {
        $genres = $this->getDoctrine()->getRepository('AppBundle:Category')->findAll();
        $books = $this->getDoctrine()->getRepository('AppBundle:Book')->findAll();
        return $this->render('@App/Main/index.html.twig', array(
            'genres' => $genres,
            'books' => $books
        ));
    }


    /**
     * @Route("/category/{id}", requirements={"id" : "\d+"}, name="category")
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function changeCategoryAction($id)
    {
        $category = $this->getDoctrine()->getRepository('AppBundle:Category')->find($id);
        $genres = $this->getDoctrine()->getRepository('AppBundle:Category')->findAll();
        $books = $category->getBooks();
        return $this->render('@App/Main/category.html.twig', [
            'books' => $books,
            'genres' => $genres
        ]);
    }


    /**
     * @Route("/registration", name="registration")
     * @param Request $request
     * @return Response
     */
    public function registrationAction(Request $request)
    {
        $reader = new Reader();

        $form_builder = $this->createFormBuilder($reader);
        $form_builder->add('fullName', TextType::class, array('label' => 'ФИО'));
        $form_builder->add('address', TextType::class, array('label' => 'Адрес'));
        $form_builder->add('passport', TextType::class, array('label' => 'ID Пасспорта'));
        $form_builder->add('save', SubmitType::class, array('label' => 'Получить читательсикй билет'));
        $form = $form_builder->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reader = $form->getData();
            $library_card = md5(date('i-s'));
            $reader->setLibraryCard($library_card);

            $em = $this->getDoctrine()->getManager();
            $em->persist($reader);
            $em->flush();

            return $this->render('@App/Main/success.html.twig', array(
                'card' => $library_card
            ));
        }
        return $this->render('@App/Main/register.html.twig', array(
            'form' => $form->createView()
        ));

    }


    /**
     * @Route("/book/{id}", requirements={"id" : "\d+"}, name="getBook")
     * @param Request $request
     * @param $id
     * @return Response
     */
    public function getBookAction(Request $request, $id)
    {
        $book = $this->getDoctrine()->getRepository('AppBundle:Book')->find($id);

        $card_id = $request->get('card_id');
        $date = $request->get('date');
        if (!empty(trim($card_id)) && !empty(trim($date))) {
            $book->setExpectedReturnDate($date);
            $reader = $this->getDoctrine()
                ->getRepository('AppBundle:Reader')
                ->getReaderByCard($card_id);
            $book->addReader($reader[0]);
            $book->setStatus(false);
            $em = $this->getDoctrine()->getManager();
            $em->persist($book);
            $em->flush();
            return $this->redirectToRoute('homepage');
        }
        return $this->render('@App/Main/getbook.html.twig', [
            'book' => $book
        ]);
    }


    /**
     * @Route("/my/books", name="my_books")
     * @return Response
     */
    public function myBooksAction()
    {
        return $this->render('@App/Main/mybooks.html.twig', [
            //
        ]);
    }


    /**
     * @Route("/my/books/get", name="get_my_books")
     * @param Request $request
     * @Method("GET")
     * @return JsonResponse
     */
    public function getMyBooksAction(Request $request)
    {
        $reader = $this->getDoctrine()
            ->getRepository('AppBundle:Reader')
            ->getReaderByCard($request->get('card_id'));
        $response_array = [];
        $books = $reader[0]->getBooks();
        foreach ($books as $book) {
            $response_array[] = [
                'name' => $book->getName(),
                'img' => $book->getImageName(),
                'author' => $book->getAuthor()
            ];
        }

        return new JsonResponse([
            'books' => $response_array
        ]);

    }


    /**
     * @Route("/{_locale}/", requirements = {"_locale" : "en|ru"}, name="change_lang")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function changeLanguageAction(Request $request)
    {
        return $this->redirect($request->headers->get('referer'));
    }

}

src/AppBundle/Resources/views/Main/category.html.twig
{% extends '@App/Main/index.html.twig' %}

{% block title %}
    {{ 'bibliography'|trans }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}
{% block body %}
    {{ parent() }}
{% endblock %}

src/AppBundle/Resources/views/Main/getbook.html.twig
{% extends 'AppBundle:Main:register.html.twig' %}

{% block title %}
    {{ book.name }}
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <style>
        .wrapper p {
            font-weight: bolder;
            font-size: 20px;
            margin: 8px;
        }
        .wrapper input {
            width: 200px;
        }
    </style>
{% endblock %}


{% block body %}
    <div class="wrapper">
        <span><a href="{{ path('homepage') }}">{{ 'come back'|trans }}</a></span>
        <p>{{ 'author'|trans }}: {{ book.author }}</p>
        <p>{{ 'name'|trans }}: {{ book.name }}</p>
        <form action="{{ path('getBook', {'id' : book.id}) }}">
            <label for="card-number">{{ 'your ticket number'|trans }}</label><br>
            <input type="text" id="card-number" name="card_id"><br>
            <label for="">{{ 'return date'|trans }}</label><br>
            <input type="text" name="date" placeholder="{{ 'example'|trans }}: 2019-8-8"><br>
            <input type="submit" value="{{ 'apply'|trans }}">
        </form>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Main/index.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ 'bibliography'|trans }}{% endblock %}
{% block stylesheets %}
    <style>
        body {
            margin: 0;
            padding: 0;
            word-wrap: break-word;
        }
        body a {
            text-decoration: none;
        }
        body a:hover {
            text-decoration: underline;
        }
        * {
            box-sizing: border-box;
        }
        header {
            margin: 0;
            padding: 10px;
            background: white;
            box-shadow: 0 2px 5px grey;
            z-index: 100;
        }
        .container {
            width: 1000px;
            margin: 0 auto;
            position: relative;
        }
        .container h1 {
            display: inline-block;
        }
        #register {
            position: absolute;
            top: 10px;
            right: 10px;
            text-decoration: none;
            color: black;
            border: 1px solid black;
            padding: 5px 20px;
        }
        .sidebar {
            width: 28%;
            background: #f0f0f0;
            padding: 10px;
        }
        .books-block {
            width: 68%;
            padding: 5px;
        }
        .genres {
            border-collapse: collapse;
        }
        .genres td {
            border-bottom: 1px solid black;
            border-top: 1px solid black;
            padding: 2px 10px;
            font-size: 20px;
        }
        .book {
            width: 40%;
            padding: 5px;
            margin: 10px 30px;
            border: 1px solid lightgrey;
            border-radius: 5px;
        }
        .book:hover {
            background: #f9f9f9;
            border: 1px solid #a8a8a8;
        }
        .books-block {
            background: #f0f0f0;
        }
        .book p {
            margin: 5px;
        }
        .get-button {
            padding: 3px 50px;
            text-decoration: none;
            background: #b3ebf0;
            border: 1px solid black;
            border-radius: 5px;
            color: black;
            margin: 5px;
        }
        .change-lang {
            display: inline-block;
            margin-left: 500px;
        }
    </style>
{% endblock %}

{% block body %}
    <header>
        <div class="container">
            <h1 style="margin: 5px; border-right: 2px solid black; padding: 0 10px">{{ 'literature'|trans }}</h1>
            <a href="{{ path('my_books') }}">{{ 'my books'|trans }}</a>
            <a href="{{ path('registration') }}" id="register">{{ 'registration'|trans }}</a>
            <div class="change-lang">
                <a href="{{ path('change_lang', {'_locale' : 'ru'}) }}">ру</a>
                <a href="{{ path('change_lang', {'_locale' : 'en'}) }}">en</a>
            </div>
        </div>
    </header>
    <div class="container" style="display: flex; flex-flow: row nowrap; justify-content: space-around; margin: 10px auto">
        <div class="sidebar">
            <h2>{{ 'genres'|trans }}:</h2>
            <table class="genres">
                <tr>
                    <td><a href="{{ path('homepage') }}">{{ 'all'|trans }}</a></td>
                </tr>
                {% for genre in genres %}
                    <tr><td><a href="{{ path('category', {'id' : genre.id}) }}">{{ genre.name }}</a></td></tr>
                {% endfor %}
            </table>
        </div>
        <div class="books-block" style="display: flex; flex-flow: row wrap; justify-content: flex-start">
            {% for book in books %}
                <div class="book" style="text-align: center">
                    <div class="book-img" style="text-align: center">
                        <img src="{{ vich_uploader_asset(book, 'imageFile') }}" alt="image" height="150">
                    </div>
                    <p>{{ 'author'|trans }}: {{ book.author }}</p>
                    <p>{{ 'name'|trans }}: "{{ book.name }}"</p>
                    {% if book.stock %}
                    <a href="{{ path('getBook', {'id' : book.id}) }}" class="get-button">{{ 'get'|trans }}</a>
                    {% else %}
                     <span style="margin: 10px; color: #5e5e5e; font-size: 14px">
                         {{ 'expected'|trans }}:
                         {{ book.expectedReturnDateString }}
                     </span>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Main/mybooks.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}
{% block stylesheets %}
    <style>
        .wrapper {
            width: 800px;
            margin: 100px auto;
            padding: 20px;
            box-shadow: 0 2px 10px grey;
            text-align: center;
        }
        .wrapper input {
            margin: 10px;
        }
        #card_id {
            width: 300px;
        }
        .books-block {
            display: flex;
            flex-flow: row wrap;
            justify-content: flex-start
        }
        .book {
            width: 40%;
            padding: 5px;
            margin: 10px 30px;
            border: 1px solid lightgrey;
            border-radius: 5px;
        }
        .book:hover {
            background: #f9f9f9;
            border: 1px solid #a8a8a8;
        }
        .books-block {
            background: #f0f0f0;
            margin: 50px 0;
        }
        .book p {
            margin: 5px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="wrapper">
        <a href="{{ path('homepage') }}">{{ 'come back'|trans }}</a><br>
        <h2>{{ 'my books'|trans }}</h2>
        <label for="card">{{ 'enter'|trans }} {{ 'your ticket number'|trans }}</label><br>
        <input type="text" id="card_id"><br>
        <button id="get_button">{{ 'apply'|trans }}</button>
        <div class="books-block">

        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        let button = $('#get_button');
        let card_id = $('#card_id');
        let books_block = $('.books-block');
        button.on('click', function () {
            $.get('/my/books/get', {card_id: card_id.val()}, function (books) {
                $(books_block).html('');
                $.each(books, function (i, book) {
                    $.each(book, function (i, book) {
                    books_block.append(`<div class="book">
                    <div class="book-img" style="text-align: center">
                        <img src="/images/books/${book.img}" alt="image" height="150">
                    </div>
                    <p>{{ 'author'|trans }}: ${book.author}</p>
                    <p>{{ 'name'|trans }}: "${book.name}"</p>
                    </div>`);
                    });
                })
            })
        })
    </script>
{% endblock %}

src/AppBundle/Resources/views/Main/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'registration'|trans }}
{% endblock %}
{% block stylesheets %}
    <style>
        .wrapper {
            box-sizing: border-box;
            width: 400px;
            height: 300px;
            position: absolute;
            left: calc(50% - 200px);
            top: calc(50% - 150px);
            box-shadow: 0 2px 10px grey;
            padding: 20px;
            text-align: center;
        }
        .wrapper input {
            margin: 10px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="wrapper">
        <span style="font-size: 12px"><a href="{{ path('homepage') }}">{{ 'come back'|trans }}</a></span>
        <h1>{{ 'registration'|trans }}:</h1>
        {{ form(form) }}
    </div>
{% endblock %}
{% block javascripts %}
{% endblock %}

src/AppBundle/Resources/views/Main/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}
 {{ 'you have successfully registered'|trans }}
{% endblock %}
{% block stylesheets %}
    <style>
        body {
            text-align: center;
            padding-top: 100px;
        }
    </style>
{% endblock %}
{% block body %}
    <h1>{{ 'you have successfully registered'|trans }}</h1>
    <h2>{{ 'your ticket number'|trans }}: <mark>{{ card }}</mark></h2>
    <p><a href="{{ path('homepage') }}">{{ 'continue'|trans }}</a></p>
{% endblock %}